require("lazy").setup({
	require("plugins/catppuccin"),
	"tpope/vim-sleuth",
	{ "numToStr/Comment.nvim", opts = {} },
	require("plugins/treesitter"),
	"nvim-treesitter/nvim-treesitter-textobjects",
	require("plugins/gitsigns"),
	require("plugins/which-key"),
	require("plugins/telescope"),
	require("plugins/lspconfig"),
	require("plugins/conform"),
	require("plugins/cmp"),
	require("plugins/todo-comments"),
	require("plugins/mini"),
	require("plugins/debug"),
	require("plugins/indent_line"),
	require("plugins/lint"),
	require("plugins/autopairs"),
	{ "uga-rosa/ccc.nvim", opts = {} },
	"unblevable/quick-scope",
	{
		"otavioschwanck/arrow.nvim",
		opts = { show_icons = true, leader_key = "<Leader><Leader>", buffer_leader_key = "m" },
	},
	require("plugins/leap"),
	require("plugins/vimtex"),
	require("plugins/tmux-navigation"),
	-- require("plugins/nnn"),
	"HiPhish/rainbow-delimiters.nvim",
	-- { "stevearc/oil.nvim", opts = {} },
	{ "andweeb/presence.nvim", opts = { neovim_image_text = "Neovim", main_image = "file", buttons = false } },
	-- { "zbirenbaum/copilot.lua", opts = { suggestion = { enabled = false }, panel = { enabled = false } } },
	-- { "zbirenbaum/copilot-cmp", opts = {} },
	{
		"iamcco/markdown-preview.nvim",
		cmd = { "MarkdownPreviewToggle", "MarkdownPreview", "MarkdownPreviewStop" },
		ft = { "markdown" },
		build = function()
			vim.fn["mkdp#util#install"]()
		end,
	},
})
