require("lazy").setup({
	require("plugins/catppuccin"),
	"tpope/vim-sleuth",
	{ "numToStr/Comment.nvim", opts = {} },
	require("plugins/treesitter"),
	"nvim-treesitter/nvim-treesitter-textobjects",
	require("plugins/gitsigns"),
	require("plugins/which-key"),
	require("plugins/telescope"),
	require("plugins/lspconfig"),
	require("plugins/conform"),
	require("plugins/cmp"),
	require("plugins/todo-comments"),
	require("plugins/mini"),
	require("plugins/debug"),
	require("plugins/indent_line"),
	require("plugins/lint"),
	require("plugins/autopairs"),
	-- require("plugins/neo-tree"),
	require("plugins/lualine"),
	{ "uga-rosa/ccc.nvim", opts = {} },
	"unblevable/quick-scope",
	{
		"otavioschwanck/arrow.nvim",
		opts = { show_icons = true, leader_key = "<Leader><Leader>", buffer_leader_key = "m" },
	},
	require("plugins/leap"),
	require("plugins/vimtex"),
	require("plugins/tmux-navigation"),
	require("plugins/nnn"),
	"HiPhish/rainbow-delimiters.nvim",
})
